### ISSUE TITLE
Create Wiki for server repository

### ISSUE THREAD

**Issue by Jadbenn** [LateBox/server#6]

**Comment by tahelmo** [comment]
The wiki for the server side was created it will be filled with information as the app is developed.

**Comment by tahelmo** [comment]
The wiki for the server side was created it will be filled with information as the app is developed.
https://github.com/LateBox/server/wiki

**Comment by tahelmo** [comment]
The wiki for the server side was created it will be filled with information as the app is developed.

https://github.com/LateBox/server/wiki
